option(
        'markdown',
        type : 'feature',
        value : 'auto',
        description : 'Build the optional markdown.ltm module (requires md4c and md4c-html)')

option(
        'zlib',
        type : 'feature',
        value : 'auto',
        description : 'Build the optional zlib.ltm module (requires zlib)')

option(
        'crypto-sodium',
        type : 'feature',
        value : 'auto',
        description : 'Build the optional crypto-sodium.ltm module (requires libsodium)')

option(
        'xml',
        type : 'feature',
        value : 'auto',
        description : 'Build the optional xml.ltm module (requires Expat)')

option(
        'curl',
        type : 'feature',
        value : 'auto',
        description : 'Build the optional curl.ltm module (requires libcurl)')
